ALTER TABLE `modlog`
	ADD COLUMN IF NOT EXISTS `id`              CHAR(12)      NOT NULL,
	ADD COLUMN IF NOT EXISTS `entry_id`        MEDIUMINT(8)  UNSIGNED NOT NULL,
	ADD COLUMN IF NOT EXISTS `guild_id`        VARCHAR(21)   NOT NULL,
	ADD COLUMN IF NOT EXISTS `message_id`      VARCHAR(21)   DEFAULT NULL,
	ADD COLUMN IF NOT EXISTS `strike_id`       CHAR(12)      DEFAULT NULL,
	ADD COLUMN IF NOT EXISTS `target`          VARCHAR(21)   NOT NULL,
	ADD COLUMN IF NOT EXISTS `blame`           VARCHAR(21)   NOT NULL,
	ADD COLUMN IF NOT EXISTS `reason`          TINYTEXT      DEFAULT NULL,
	ADD COLUMN IF NOT EXISTS `type`            TINYTEXT      NOT NULL,
	ADD COLUMN IF NOT EXISTS `created_at`      BIGINT(20)    UNSIGNED NOT NULL,
	ADD COLUMN IF NOT EXISTS `last_edited_at`  BIGINT(20)    UNSIGNED DEFAULT NULL,
	ADD COLUMN IF NOT EXISTS `last_edited_by`  VARCHAR(21)   DEFAULT NULL,
	ADD COLUMN IF NOT EXISTS `delete_days`     INT(10)       UNSIGNED DEFAULT NULL,
	ADD COLUMN IF NOT EXISTS `timed_id`        VARCHAR(12)   DEFAULT NULL,
	ADD COLUMN IF NOT EXISTS `warning_id`      TINYINT(3)    UNSIGNED DEFAULT NULL,
	ADD COLUMN IF NOT EXISTS `total`           INT(10)       UNSIGNED DEFAULT NULL,
	ADD COLUMN IF NOT EXISTS `active`          TINYINT(1)    DEFAULT NULL,
	-- Indexes
	ADD UNIQUE INDEX IF NOT EXISTS `id`            (`id`),
	ADD UNIQUE INDEX IF NOT EXISTS `entryid_guild` (`entry_id`,`guild_id`),
	ADD UNIQUE INDEX IF NOT EXISTS `message_id`    (`message_id`),
	ADD UNIQUE INDEX IF NOT EXISTS `strike_id`     (`strike_id`),
	ADD INDEX IF NOT EXISTS        `entry_id`      (`entry_id`),
	ADD INDEX IF NOT EXISTS        `guild_id`      (`guild_id`),
	ADD INDEX IF NOT EXISTS        `target`        (`target`),
	ADD INDEX IF NOT EXISTS        `blame`         (`blame`),
	ADD INDEX IF NOT EXISTS        `timed_id`      (`timed_id`),
	-- Foreign Keys
	ADD CONSTRAINT `fk_modlog_guildid`  FOREIGN KEY IF NOT EXISTS (`guild_id`)  REFERENCES `guilds`  (`id`),
	ADD CONSTRAINT `fk_modlog_strikeid` FOREIGN KEY IF NOT EXISTS (`strike_id`) REFERENCES `strikes` (`id`),
	ADD CONSTRAINT `fk_modlog_timedid`  FOREIGN KEY IF NOT EXISTS (`timed_id`)  REFERENCES `timed`   (`id`);
