CREATE TABLE `modlog` (
	`id` CHAR(12) NOT NULL,
	`entry_id` MEDIUMINT(8) UNSIGNED NOT NULL,
	`guild_id` VARCHAR(21) NOT NULL,
	`message_id` VARCHAR(21) DEFAULT NULL,
	`strike_id` CHAR(12) DEFAULT NULL,
	`target` VARCHAR(21) NOT NULL,
	`blame` VARCHAR(21) NOT NULL,
	`reason` TINYTEXT DEFAULT NULL,
	`type` TINYTEXT NOT NULL,
	`created_at` BIGINT(20) UNSIGNED NOT NULL,
	`last_edited_at` BIGINT(20) UNSIGNED DEFAULT NULL,
	`last_edited_by` VARCHAR(21) DEFAULT NULL,
	`delete_days` INT(10) UNSIGNED DEFAULT NULL,
	`timed_id` VARCHAR(12) DEFAULT NULL,
	`warning_id` TINYINT(3) UNSIGNED DEFAULT NULL,
	`total` INT(10) UNSIGNED DEFAULT NULL,
	`active` TINYINT(1) DEFAULT NULL,
	PRIMARY KEY (`id`),
	UNIQUE KEY `id` (`id`),
	UNIQUE KEY `entryid_guild` (`entry_id`,`guild_id`),
	UNIQUE KEY `message_id` (`message_id`),
	UNIQUE KEY `strike_id` (`strike_id`),
	KEY `entry_id` (`entry_id`),
	KEY `guild_id` (`guild_id`),
	KEY `target` (`target`),
	KEY `blame` (`blame`),
	KEY `timed_id` (`timed_id`)
);
