services:
  maidboye:
    build: .
    container_name: maidboye
    profiles:
      - all
    volumes:
      - modules:/app/node_modules
      - build:/app/build
      - ./data/bot:/data
      - /etc/hostname:/data/hostname
    environment:
      DOCKER: 1
    restart: always
    healthcheck:
      interval: 10s
      timeout: 2s
      test: lsof -i :8080 || exit 1
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    hostname: maidboye.bots.containers.local
    networks:
      default:
        ipv4_address: 172.19.3.2
      websites:
        ipv4_address: 172.19.2.250

  postgres:
    image: postgres:14-alpine
    container_name: postgres.maidboye
    profiles:
      - all
      - db
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./src/db/migrations:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    environment:
      - POSTGRES_USER=maidboye
      - POSTGRES_DB=maidboye
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      interval: 5s
      timeout: 2s
      test: pg_isready -U maidboye
    networks:
      default:
        ipv4_address: 172.19.3.3

  redis:
    image: redis:alpine
    container_name: redis.maidboye
    profiles:
      - all
      - db
    command: redis-server --save 10 1 --loglevel warning
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
    networks:
      default:
        ipv4_address: 172.19.3.4

networks:
  default:
    name: maidboye
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.3.0/29
          gateway: 172.19.3.1
  websites:
    name: websites
    external: true

volumes:
  modules:
  build:
