services:
  maidboye:
    image: ghcr.io/donovandmc/maidboye
    container_name: maidboye
    volumes:
      - ./data/bot:/data
      - /etc/hostname:/data/hostname
    restart: always
    healthcheck:
      interval: 10s
      timeout: 2s
      test: lsof -i :8080 || exit 1
    deploy:
        resources:
          limits:
            memory: 1024M
          reservations:
            memory: 256M
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    hostname: maidboye.bots.containers.local
    networks:
      default:
        ipv4_address: 172.19.3.2

  postgres:
    image: postgres:14-alpine
    container_name: postgres.maidboye
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./src/db/migrations:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    environment:
      - POSTGRES_USER=maidboye
      - POSTGRES_DB=maidboye
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      interval: 5s
      timeout: 2s
      test: pg_isready -U maidboye
    deploy:
        resources:
          limits:
            memory: 512M
          reservations:
            memory: 128M
    networks:
      default:
        ipv4_address: 172.19.3.3

  redis:
    image: redis:alpine
    container_name: redis.maidboye
    command: redis-server --save 10 1 --loglevel warning
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
    deploy:
        resources:
          limits:
            memory: 128M
          reservations:
            memory: 64M
    networks:
      default:
        ipv4_address: 172.19.3.4

networks:
  default:
    name: maidboye
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.3.0/29
          gateway: 172.19.3.1
