

version: "3"

services:
  maidboye:
    build: .
    container_name: maidboye
    volumes:
      - modules:/app/node_modules
      - build:/app/build
      - ./data/bot:/mnt/data
    environment:
      MODE: prod
      DATA_DIR: /data
      PTR: 1
    restart: always
    healthcheck:
      interval: 10s
      timeout: 2s
      test: lsof -i :8443 || exit 1
    hostname: maidboye.bots.containers.local
    ports:
      - 127.1.1.1:8443:8443
      - 127.1.1.2:8443:8443
    networks:
      default:
        ipv4_address: 172.18.0.4
  mariadb:
    image: mariadb
    container_name: mariadb.maidboye
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "$MARIADB_ROOT_PASSWORD"
    restart: always
    healthcheck:
      interval: 5s
      timeout: 2s
      test: mysqladmin --user=root --password=$$MYSQL_ROOT_PASSWORD ping
    hostname: mariadb.maidboye.containers.local
    networks:
      default:
        ipv4_address: 172.18.0.3
  redis:
    image: redis:alpine
    command: redis-server --disable-thp yes --supervised no --bind 0.0.0.0 --protected-mode no
    container_name: redis.maidboye
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
    restart: always
    hostname: redis.maidboye.containers.local
    networks:
      default:
        ipv4_address: 172.18.0.2

networks:  
  default:
    name: maidboye
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/29
          gateway: 172.18.0.1

volumes:
  build: null
  modules: null
