services:
  maidboye:
    image: ghcr.io/donovandmc/maidboye
    container_name: maidboye
    volumes:
      - ./data/bot:/data
      - /etc/hostname:/data/hostname
    restart: always
    init: true
    healthcheck:
      interval: 5s
      timeout: 1s
      test: wget -q --spider http://127.0.0.1:3621
    deploy:
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 512M
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    hostname: maidboye.containers.local
    labels:
      - "hostname=maidboye.containers.local"
      - "traefik.enable=true"
      - "traefik.http.routers.maidboye.rule=HostRegexp(`api.maidboye.cafe`)"
      - "traefik.http.routers.maidboye.entrypoints=https"
      - "traefik.http.routers.maidboye.tls=true"
      - "traefik.http.services.maidboye.loadbalancer.server.port=8080"
    networks:
      - default

  postgres:
    image: postgres:14-alpine
    container_name: postgres.maidboye
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./src/db/migrations:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    environment:
      - POSTGRES_USER=maidboye
      - POSTGRES_DB=maidboye
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      interval: 5s
      timeout: 2s
      test: pg_isready -U maidboye
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    hostname: postgres.maidboye.containers.local
    labels:
      - "hostname=postgres.maidboye.containers.local"
    networks:
      - default

  redis:
    image: redis:alpine
    container_name: redis.maidboye
    command: redis-server --save 10 1 --loglevel warning
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
    hostname: redis.maidboye.containers.local
    labels:
      - "hostname=redis.maidboye.containers.local"
    networks:
      - default

networks:
  default:
    name: maidboye
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.3.0/29
    driver_opts:
      com.docker.network.bridge.name: br-maidboye
